name: Build Maven + Docker Push

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      base_image:
        required: false
        type: string
        default: "nrt.ocir.io/idpdeuxb29fz/devops:openjdk17-alpine"
      java_version:
        required: false
        type: string
        default: "8"
      java_distribution:
        required: false
        type: string
        default: "temurin"
      env:
        required: true
        type: string
        
    secrets:
      OCIR_USERNAME:
        required: true
      OCIR_AUTH_TOKEN:
        required: true
      OCIR_NAMESPACE:
        required: true
      IMAGE_REGISTRY:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java_distribution }}
          java-version: ${{ inputs.java_version }}
          cache: maven

      - name: Checkout Template Repo
        uses: actions/checkout@v4
        with:
          repository: SimiTalk/ci-cd-template-repo
          path: template

      - name: Detect Version
        id: detect
        run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_REF_TYPE=${GITHUB_REF_TYPE}"
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"

          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION=$(echo "${GITHUB_REF_NAME}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
            if [[ -z "$VERSION" ]]; then
              echo "❌ Tag 格式必须为 release-x.y.z"
              exit 1
            fi
            IMAGE_TAG="$VERSION"
          elif [[ "${GITHUB_REF_NAME}" == "blockchain-intl" ]]; then
            IMAGE_TAG="latest"
          else
            echo "❌ 不支持的分支或 tag"
            exit 1
          fi

          echo "image_tag=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"

      - name: Build with Maven
        run: |
          mvn clean package --settings template/.github/maven/settings.xml -Dmaven.test.skip=true
          JAR=$(ls -1 target/*.jar | grep -Ev '(sources|javadoc|original)' | head -n 1)
          echo "Detected jar: $JAR"
          cp "$JAR" target/app.jar
          ls -lah target

      - name: Login to OCIR
        env:
          USER: ${{ secrets.OCIR_USERNAME }}
          PASS: ${{ secrets.OCIR_AUTH_TOKEN }}
          REG: ${{ secrets.IMAGE_REGISTRY }}
        run: |
          echo "${PASS}" | docker login "${REG}" -u "${USER}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          IMAGE="${{ secrets.IMAGE_REGISTRY }}/${{ secrets.OCIR_NAMESPACE }}/${{ inputs.service_name }}-${{ inputs.env }}:${{ steps.detect.outputs.image_tag }}"
          echo "Building: $IMAGE"
          docker build -t "$IMAGE" -f "template/docker/Dockerfile.java" --build-arg BASE_IMAGE="${{ inputs.base_image }}" .
          docker push "$IMAGE"